name: Daily Bot Run

on:
  schedule:
    # Jalan otomatis tiap hari jam 08:00 UTC (15:00 WIB)
    - cron: '0 8 * * *'
  workflow_dispatch: # Bisa jalan manual dari menu Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python bot.py
