name: Daily Bot Run

on:
  schedule:
    # Jalankan tiap hari jam 08:00 UTC (15:00 WIB)
    - cron: '0 8 * * *'
  workflow_dispatch: # Bisa dijalankan manual dari GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run bot
      run: |
        python bot.py
